import { NgModule } from '@angular/core';
import { RouterModule, Routes } from '@angular/router';
import { DialogueProductGeneraliComponent } from './dialogue-product-generali.component';
import { FormAGeneraliComponent } from './form-a/form-a-generali.component';
import {
  routesDictFromChildrenRoutes,
  childrenRoutesFromDict,
} from 'src/app/ng-dynamic-forms/form-routes';
import { dialogueProductFormRoutes } from '../dialogue-product/dialogue-product-routing.module';
import { FormCGeneraliComponent } from './form-c/form-c.component';

// Code to be personalized for each dialogue
// define the routes for the child components
const dialoguProductRoutes = dialogueProductFormRoutes;
const routesDict = routesDictFromChildrenRoutes(dialoguProductRoutes);
routesDict[''].component = FormAGeneraliComponent;
routesDict['form-a'].component = FormAGeneraliComponent;
routesDict['form-c'].component = FormCGeneraliComponent;
export const dialoguProductGeneraliFormRoutes =
  childrenRoutesFromDict(routesDict);

// this code has to be changed, with respect to the code generated by the Angular CLI,
// setting the children property with the formRoutes variable defined above
const routes: Routes = [
  {
    path: '',
    component: DialogueProductGeneraliComponent,
    children: dialoguProductGeneraliFormRoutes,
  },
];

@NgModule({
  imports: [RouterModule.forChild(routes)],
  exports: [RouterModule],
})
export class DialogueProductGeneraliRoutingModule {}
