import { NgModule } from '@angular/core';
import { RouterModule, Routes } from '@angular/router';
import { FormAComponent } from '../dialogue-product/form-a/form-a.component';
import { FormCComponent } from '../dialogue-product/form-c/form-c.component';
import { FormBSpainComponent } from './form-b-spain/form-b-spain.component';
import { ProductDialogueSpainComponent } from './dialogue-product-spain.component';
import { dialogueProductFormRoutes } from '../dialogue-product/dialogue-product-routing.module';
import {
  childrenRoutesFromDict,
  routesDictFromChildrenRoutes,
} from 'src/app/ng-dynamic-forms/form-routes';

// Code to be personalized for each dialogue
// define the routes for the child components
const dialoguProductRoutes = dialogueProductFormRoutes;
const routesDict = routesDictFromChildrenRoutes(dialoguProductRoutes);
routesDict['form-b'].component = FormBSpainComponent;
export const dialoguProductSpainFormRoutes = childrenRoutesFromDict(routesDict);

// this code has to be changed, with respect to the code generated by the Angular CLI,
// setting the children property with the formRoutes variable defined above
const routes: Routes = [
  {
    path: '',
    component: ProductDialogueSpainComponent,
    children: dialoguProductSpainFormRoutes,
  },
];

@NgModule({
  imports: [RouterModule.forChild(routes)],
  exports: [RouterModule],
})
export class DialogueProductSpainRoutingModule {}
